[package]
org = "ballerinax"
name = "candid"
version = "@toml.version@"
authors = ["Ballerina"]
export = ["candid.charitycheckpdf", "candid.essentials", "candid.premier"]
keywords = ["Candid", "Nonprofit Data", "Philanthropy Data", "Nonprofit APIs"]
repository = "https://github.com/ballerina-platform/module-ballerinax-candid"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"
